WineDB/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('database.urls')),
]

database/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
	path('', views.wine_list, name='wine_list'),
    path('winedb/<int:pk>/', views.wine_detail, name='wine_detail'),
    path('winedb/new/', views.add_new_wine, name='add_new_wine'),
    path('winedb/add_bottle/<int:pk>/', views.add_new_bottle, name= 'add_new_bottle'),
	]

database/models.py
from django.db import models
from django.conf import settings
from django.utils import timezone
from django.contrib import admin
from django.forms import ModelForm


COLOUR = [
    ('-', '-'),
    ('White', 'White'),
    ('Orange', 'Orange'),
    ('Red', 'Red'),
    ('Rose', 'Rose'),
    ('Pet Nat', 'Pet Nat'),
    
]

class Country(models.Model):
	name = models.CharField(max_length=200, null=True, blank=True)

	def __str__(self):
		return self.name

class Colour(models.Model):
	name = models.CharField(max_length=200, null=True, blank=True)

	def __str__(self):
		return self.name


class Region(models.Model):
	name = models.CharField(max_length=200, null=True, blank=True)

	def __str__(self):
		return self.name

class Grape(models.Model):
	name = models.CharField(max_length=200, null=True, blank=True)

	def __str__(self):
		return self.name

class WineType(models.Model):
	referring_wine_type = models.CharField(max_length=200, blank=True, null=True)

	def __str__(self):
		return self.referring_wine_type

class Producer(models.Model):
	referring_producer_name = models.CharField(max_length=200, blank=True, null=True)
	referring_producer_country = models.ForeignKey(Country, null=True, blank=True, on_delete=models.CASCADE)
	referring_producer_region = models.ForeignKey(Region, null=True, blank=True, on_delete=models.CASCADE)


	def __str__(self):
		return self.referring_producer_name


class Wine(models.Model):
	producer = models.ForeignKey(Producer, null=True, blank=True, on_delete=models.CASCADE, default=0)
	name = models.CharField(max_length=200)
	year = models.IntegerField(blank=True, null=True)
	alcohol = models.FloatField(blank=True, null=True)
	grape = models.ManyToManyField(Grape)
	colour = models.ForeignKey(Colour, null=True, blank=True, on_delete=models.CASCADE, default=0)
	wine_type = models.ForeignKey(WineType, null=True, blank=True, on_delete=models.CASCADE, default=0)
	notes = models.TextField(max_length=2000, blank=True, null=True)
	wishlist = models.BooleanField(default=False)
	date = models.DateField(blank=True, null=True)
	

	def __str__(self):
		return self.name


	def get_bottles(self):
		a = []
		for bottle in self.Bottle.all():
			a.append((bottle.date_bought))

		return a

	def available_bottle(self):
		number = self.Bottle.filter(available=True).count()
		return number


class Bottle(models.Model):
	wine = models.ForeignKey(Wine, related_name='Bottle', on_delete=models.CASCADE)
	date_bought = models.DateField(null=True)
	bottleprice = models.CharField(max_length=200, blank=True,)
	#notes = models.TextField(max_length=2000, blank=True, null=True)
	available = models.BooleanField(default=True)
	drank_on = models.DateField(blank=True, null=True)

	

	def __str__(self):
		return str(self.date_bought)
		
	def save(self, *args, **kwargs):
		if self.drank_on is not None:
			self.available=False

		super(Bottle, self).save(*args, **kwargs)

	

		

database/forms.py
from django import forms
from datetime import datetime
from django.forms import ModelForm

from .models import Wine, Bottle

class DateInput(forms.widgets.DateInput):
    input_type = 'date'

class WineForm(forms.ModelForm):

    class Meta:
        model = Wine
        fields = ('producer', 'name', 'year', 'alcohol', 'grape', 'colour', 'wine_type', 'notes', 'wishlist', 'date')

        widgets= {
            'date': forms.DateInput(
                attrs={'type':'date'}), 
        }

class BottleForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, *kwargs)

    class Meta:
        model = Bottle
        fields = ('wine', 'date_bought', 'bottleprice', 'available', 'drank_on') 

        widgets= {
            'date_bought': forms.DateInput(
                attrs={'type':'date'}), 
        }

# class BottleForm(forms.Form):
#     date = forms.DateField(widget=forms.DateInput(attrs={'type': 'date'}))

database/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.utils import timezone
from django import forms
from datetime import datetime
from .forms import WineForm, BottleForm
from django.forms import inlineformset_factory
from django.views.generic import ListView, DetailView, CreateView
from .models import Wine, Bottle, WineType, Country


def wine_list(request):
	wines = Wine.objects.order_by('name')
	context = {
		'wines': wines,
		# 'available_bottles': Bottle.objects.filter(available=True).count()
	}
	return render(request, 'winedb/wine_list.html', context)

def wine_detail(request, pk):
	wine = get_object_or_404(Wine, id=pk)
	bottles = wine.Bottle.all()
	context = {'wine': wine,
	'bottles': bottles}
	return render(request, 'winedb/wine_detail.html', context)


def add_new_bottle(request, pk):
	WineFormSet = inlineformset_factory(Wine, Bottle, 
		fields=('date_bought', 'bottleprice', 'available', 'drank_on'), 
		widgets= {
            'date_bought': forms.DateInput(
                attrs={'type':'date'}),
                'drank_on': forms.DateInput(
                attrs={'type':'date'}) 
        })
	wine = Wine.objects.get(id=pk)
	formset = WineFormSet(instance=wine)
	# form = BottleForm(initial={'wine':wine})
	if request.method == "POST":
		form = BottleForm(request.POST)
		if form.is_valid():
			wine = form.save(commit=False)
			wine.save()
			return redirect('/')

	context = {'formset':formset}
	return render(request, 'winedb/bottle_form.html', context)

def add_new_wine(request):
	if request.method == "POST":
		form = WineForm(request.POST)
		if form.is_valid():
			wine = form.save(commit=False)
			wine.save()
			return redirect('wine_detail', id=wine.pk)
	else:
		form = WineForm()
	return render(request, 'winedb/wine_edit.html', {'form': form})



# def bottle_count(self, obj):
# 	return obj.bottle_count

class HomeView(ListView):
	model = Wine
	template_name = 'home.html'

class WineDetailView(DetailView):
	model = Wine
	template_name = 'wine_detail.html'

database/templates/winedb/base.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
        <script src="https://code.jquery.com/jquery-3.7.1.min.js" integrity="sha256-/JqT3SQfawRcv/BIHPThkBvs0OEvtFFmqPF/lYI/Cxo=" crossorigin="anonymous"></script>
        <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
        <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
        <link rel="stylesheet" href="{% static 'css/database.css' %}">
        <title>Mickey's Wine List</title>
    </head>
    <body>
    <header class="page-header">
      <div class="container">
          <h1><a href="/">Mickey's Wine List</a></h1>
          
      </div>

      <div class="container">
                <a href="{% url 'add_new_wine' %}" class="top-menu"> ADD NEW
                </a>
            </div>
    </header>
    <main class="container">
        <div class="row">
            <div class="col">
            {% block content %}
            {% endblock %}
            </div> 
        </div>


    </main>

    {% block script %}

    {% endblock %}
</body>
</html>

database/templates/winedb/bottle_form.html
{% extends 'winedb/base.html' %}
{% load crispy_forms_tags %}

{% block content %}
    <h2>New Bottle</h2>
    <form method="POST" class="post-form">{% csrf_token %}
        {% for form in formset%}
            {{ form|crispy }}
            <hr>
        {% endfor %}
        <button type="submit" class="save btn btn-secondary">Save</button>
    </form>
{% endblock %}

<!-- {% block script %}


<script>
    
    $("#id_grape").select2();
</script>

{% endblock %} -->

database/templates/winedb/wine_detail.html
{% extends 'winedb/base.html' %}

{% block content %}
    <h2>Back to list</h2>
    
    <!-- <style>
        table, th, td {
          border: 0px solid black;
          border-collapse: collapse;
          padding-left: 5px;
          padding-right: 5px;

        }

        tr:nth-child(even) {
              background-color: #D6EEEE;
            }
        .unavailable:nth-child(even) {
            background-color: #EEBBBB !important;
            text-decoration: line-through;
                    }
        .unavailable:nth-child(odd) {
            background-color: #EEA0A0 !important;
            text-decoration: line-through;
                    }
</style>
 -->
<table class="table table-striped">
    <tr>
        <td>Producer </td>
        <td>{{ wine.producer }} </td>
    </tr>
    <tr>
        <td>Name </td>
        <td>{{ wine.name }} </td>
    </tr>
    <tr>
        <td>Country </td>
        <td>{{ wine.producer.referring_producer_country }} </td>
    </tr>
    <tr>
        <td>Region </td>
        <td>{{ wine.producer.referring_producer_region }} </td>
    </tr>
    <tr>
        <td>Year </td>
        <td>{{ wine.year }} </td>
    </tr>
    <tr>
        <td>Percentage </td>
        <td>{{ wine.alcohol }} </td>
    </tr>
    <tr>
        <td>Grape </td>
        <td>{% for grape in wine.grape.all %}{{ grape }}{% if not forloop.last %}, {% endif %} {% endfor %}</td>
    </tr>
    <tr>
        <td>Variety </td>
        <td>{{ wine.wine_type.referring_wine_type }} </td>
    </tr>
    <tr>
        <td>Notes </td>
        <td>{{ wine.notes|linebreaks }} </td>
    </tr>


</table>

<br>

<h3> BOTTLES </h3>
    <a class="btn btn-outline-info btn-sm btn-block" href="{% url 'add_new_bottle' wine.id %}">ADD NEW BOTTLE</a>
    <br><br>

<table class="table table-striped">
    
</style>
    
    <tr>
        <th>Date Bought</th>
        <th>Price</th>
        <th>Date Drank</th>
        <th>Notes</th>
        
    </tr>
    {% for bottle in bottles %}

        <tr class="{% if bottle.available is False %}table-danger{% endif %}">
            <td>
        {{ bottle.date_bought }}
            </td>

             <td>
        {{ bottle.bottleprice }}
            </td>

            <td>
        {{ bottle.drank_on }}
            </td>

            <td>
        {{ bottle.notes }}
            </td>

        </tr>
        
    {% endfor %}

</table>


{% endblock %}

database/templates/winedb/wine_edit.html
{% extends 'winedb/base.html' %}
{% load crispy_forms_tags %}

{% block content %}
    <h2>New wine</h2>
    <form method="POST" class="post-form">{% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="save btn btn-secondary">Save</button>
    </form>
{% endblock %}

{% block script %}


<script>
    
    $("#id_producer").select2({
        tags: true
    });

    $("#id_grape").select2({
        tags: true
    });
</script>

{% endblock %}

database/templates/winedb/wine_list.html
{% extends 'winedb/base.html' %}

{% block content %}
<style>

</style>

<table class="table table-striped">
    <tr>
        <th scope="col">Producer</th>
        <th scope="col">Name</th>
        <th scope="col">Country</th>
        <th scope="col">Region</th>
        <th scope="col">Available Bottles</th>

    </tr>
    {% for wine in wines %}
    <tr>
        <td>
            <a href="{% url 'wine_detail' wine.id %}"> {{ wine.producer }} </a>
        </td>

        <td>

    {{ wine.name }}
        </td>

         <td>

    {{ wine.producer.referring_producer_country }}
        </td>

        <td>

    {{ wine.producer.referring_producer_region }}
        </td>

        <td>

    {{ wine.available_bottle }}
    </tr>
    {% endfor %}

{% endblock %}